### ISSUE TITLE
Library breaks with Python 3.8

### ISSUE THREAD

**Issue by pranaynanda** [googleapis/python-cloudbuild#35]
#### Environment details

  - OS type and version: MacOS
  - Python version: `python --version`: Python 3.7
  - pip version: `pip --version`
  - `google-cloud-build` version: `pip show google-cloud-build`

Name: google-cloud-build
Version: 2.0.0
Summary: Google Cloud Build API client library
Home-page: https://github.com/googleapis/python-cloudbuild
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/pranaynanda/Library/Python/3.7/lib/python/site-packages
Requires: proto-plus, libcst, google-api-core
Required-by: 

#### Steps to reproduce

  1. Deploy the following code as Google Cloud Function
  2. Test the code from the Cloud Function console

#### Code example

```
import base64
import os
from google.cloud.devtools import cloudbuild_v1
client = cloudbuild_v1.CloudBuildClient()
project_id = os.environ.get('GCP_PROJECT')
build = {
    "steps": [{
        "name": "gcr.io/cloud-builders/gcloud",
        "entrypoint":"bash",
        "args": [
        "-c",
        "gcloud projects delete $PROJECT_ID"
      ]
    }]
}

def hello_pubsub(event, context):
    """Triggered from a message on a Cloud Pub/Sub topic.
    Args:
         event (dict): Event payload.
         context (google.cloud.functions.Context): Metadata for the event.
    """
    print("event:", event)
    print("context:", context)
    response = client.create_build(
            project_id=os.environ.get('GCP_PROJECT'),
            build=cloudbuild_v1.Build(build),
)
    # print(response)
```

#### Stack trace
```
Traceback (most recent call last): File "/layers/google.python.functions-framework/functions-framework/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.functions-framework/functions-framework/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.functions-framework/functions-framework/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.functions-framework/functions-framework/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.functions-framework/functions-framework/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.functions-framework/functions-framework/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.functions-framework/functions-framework/functions_framework/__init__.py", line 102, in view_func function(data, context) File "/workspace/main.py", line 25, in hello_pubsub response = client.create_build( File "/layers/google.python.pip/pip/google/cloud/devtools/cloudbuild_v1/services/cloud_build/client.py", line 324, in create_build response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,) File "/layers/google.python.pip/pip/google/api_core/gapic_v1/method.py", line 145, in __call__ return wrapped_func(*args, **kwargs) File "/layers/google.python.pip/pip/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable six.raise_from(exceptions.from_grpc_error(exc), exc) File "<string>", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 503 Policy checks are unavailable.
```

If I change the runtime to Python 3.7, it works perfectly as expected.

**Comment by busunkim96** [comment]
I'm not sure this is related to Python 3.7/3.8, since the failures is Service Unavailable 503.

**Comment by pranaynanda** [comment]
Works perfectly when runtime changes.

**Comment by busunkim96** [comment]
@pranaynanda There's nothing different about the deployments besides the runtime? Do you always see the same error?

3.8 has been out for long enough that I think we would have heard about an issue specific to the generated clients.

**Comment by pranaynanda** [comment]
Yes, the error is always the same and nothing changed besides the runtime.

**Comment by dinagraves** [comment]
Unable to recreate.  Tried this with 3.7 and 3.8:

`import base64
import os
from google.cloud.devtools import cloudbuild_v1

def hello_pubsub(event, context):
    """Triggered from a message on a Cloud Pub/Sub topic.
    Args:
         event (dict): Event payload.
         context (google.cloud.functions.Context): Metadata for the event.
    """
    pubsub_message = base64.b64decode(event['data']).decode('utf-8')

    client = cloudbuild_v1.CloudBuildClient()
    build = {
        "steps": [{"name": "ubuntu", 
                "entrypoint": "bash",
                "args": ["-c", f"echo {pubsub_message}"]
                }]
    }

    operation = client.create_build(
            project_id=PROJECT_ID,
            build=cloudbuild_v1.Build(build),
            )
    print(operation.metadata.build.log_url)`

Both worked fine.

**Comment by sdenef-adeo** [comment]
FYI the GCP_PROJECT env var is no more provided with Python runtime >= 3.8
https://cloud.google.com/functions/docs/env-var#newer_runtimes

Hope this helps
