### ISSUE TITLE
e2-* machine types not supported

### ISSUE THREAD

**Issue by simond** [googleapis/python-cloudbuild#62]
While trying to run a Cloud Build job with one of the newer "E" machine types as described on the [pricing page](https://cloud.google.com/cloud-build/pricing). Getting an error which suggests they are not yet supported through the client libraries... The "N" machine types seem fine. 

#### Environment details

  - OS type and version: **macOS 11.i (Big Sur)**
  - Python version: **3.8.0**
  - pip version: **21.0**
  - `google-cloud-build` version: 
```Name: google-cloud-build
Version: 3.0.0
Summary: Google Cloud Build API client library
Home-page: https://github.com/googleapis/python-cloudbuild
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/repos/project/venv/lib/python3.8/site-packages
Requires: proto-plus, libcst, google-api-core
Required-by:
```

#### Steps to reproduce

  1. Create a `cloudbuild.Build` object using any of the e2* machine types in the `options` field.
  2. Make a call to `cloudbuild.CloudBuildClient.create_build`
  3. Get error

#### Code example

```python
from google.cloud.devtools import cloudbuild


def main():
    cb_client = cloudbuild.CloudBuildClient()
    build = cloudbuild.Build({
        'steps': [{
            'id': 'Build Docker image',
            'name': 'gcr.io/cloud-builders/docker',
            'entrypoint': 'sh',
            'args': ['-c', 'echo ========== Hi there ==============']
        }],
        'options': {
            'machine_type': 'E2_HIGHCPU_32'
        },
    })

    build = cb_client.create_build(project_id='my-project', build=build)
    result = build.result()
    print(result)


if __name__ == "__main__":
    main()

```

#### Stack trace
```
/Users/repos/project/venv/bin/python /Users/repos/project/testing.py
Traceback (most recent call last):
  File "/Users/repos/project/testing.py", line 24, in <module>
    main()
  File "/Users/repos/project/testing.py", line 6, in main
    build = cloudbuild.Build({
  File "/Users/repos/project/venv/lib/python3.8/site-packages/proto/message.py", line 466, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/Users/repos/project/venv/lib/python3.8/site-packages/proto/marshal/marshal.py", line 205, in to_proto
    pb_value = rule.to_proto(value)
  File "/Users/repos/project/venv/lib/python3.8/site-packages/proto/marshal/rules/message.py", line 32, in to_proto
    return self._descriptor(**value)
ValueError: unknown enum label "E2_HIGHCPU_32"
```

**Comment by dinagraves** [comment]
Which version of the API are you using?  google-cloud-build==3.2.0 works for me as you wrote it.   Please feel free to reopen if you're still experiencing the issue.

**Comment by simond** [comment]
Version 3.0.0 as shown in the issue description.

**Comment by simond** [comment]
> Which version of the API are you using? 

Version 3.0.0 as shown in the issue description.
